import {
  ArrowBigRight,
  BadgeDollarSign,
  BookHeadphones,
  CalendarCheck,
  ChartNoAxesGantt,
  CircleUser,
  createLucideIcon,
  Eye,
  EyeOff,
  Home,
  LogOut,
  Mail,
  MessageCircleWarning,
  Settings,
  ShieldHalf,
  Table,
  User,
  UserCheck,
  UserCircle2,
  UserCog,
  UserPlus,
} from 'lucide-react';
export const Icons = {
  Profile: UserCog,
  ManageStudent: UserCircle2,
  ManageFaculty: UserCheck,
  ManageAcademic: ChartNoAxesGantt,
  AcademicReport: MessageCircleWarning,
  Management: CircleUser,
  ManageAdmin: Settings,
  ManageUser: User,
  ManagePermissions: UserPlus,
  ManageTableList: Table,
  FacultyCourse: ShieldHalf,
  StudentRegistration: UserPlus,
  StudentPayment: BadgeDollarSign,
  StudentCourse: BookHeadphones,
  StudentCourseSchedules: CalendarCheck,
  Create: createLucideIcon,
  Home: Home,
  Logout: LogOut,
  ArrowRight: ArrowBigRight,
  Mail: Mail,
  Eye: Eye,
  EyeOff: EyeOff,
};
